### ISSUE TITLE
Feature: print bibliography at the end of markdown by default without the mark

### ISSUE THREAD

**Issue by ryushinn** [arothuis/markdown-it-biblatex#15]
Hi, I am looking for an option to switch from printing the bibliography at the position of the mark (e.g., [bibliography]), **to just printing it at the end of the document without any mark.** The latter is the default behaviour of the Pandoc markdown parser, and is what 95% academic articles will do.

The "mark" feature is very great, flexible, and legit but also could bother writers to some degree, by asking them to put the marks constantly. 

By removing the marks, the markdown file could benefit from the clearness and portability (those parsers that do not support the mark feature will throw plain texts or even errors back). And since the [@xxx] is the _Pandoc-style_ citation, I think it is more reasonable to align with what Pandoc does.

Thanks for your time reading this. Your update will be highly appreciated.

**Comment by arothuis** [comment]
Full compatibility with pandoc is not a goal of this library. 

That being said, I'm not opposed to adding a feature `appendBibliographyWithoutMark` or something like that. It does take some time to research a good solution for this. I don't know how difficult it is to append something to the end of the document.

**Comment by ryushinn** [comment]
Yes, I would be happy to see this feature.

**Comment by VikramSinghMTL** [comment]
Hi, I think this feature would be great too! Can we merge #17?
